'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace REY_PressMate.Settings
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")>  _
    Partial Friend NotInheritable Class Settings_FIS
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As Settings_FIS = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings_FIS()),Settings_FIS)
        
        Public Shared ReadOnly Property [Default]() As Settings_FIS
            Get
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192.168.10.18")>  _
        Public Property IP() As String
            Get
                Return CType(Me("IP"),String)
            End Get
            Set
                Me("IP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Enabled() As Boolean
            Get
                Return CType(Me("Enabled"),Boolean)
            End Get
            Set
                Me("Enabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("32000")>  _
        Public Property Port() As Integer
            Get
                Return CType(Me("Port"),Integer)
            End Get
            Set
                Me("Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5000")>  _
        Public Property SendTimeout() As Integer
            Get
                Return CType(Me("SendTimeout"),Integer)
            End Get
            Set
                Me("SendTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5000")>  _
        Public Property RecieveTimeout() As Integer
            Get
                Return CType(Me("RecieveTimeout"),Integer)
            End Get
            Set
                Me("RecieveTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NoDelay() As Boolean
            Get
                Return CType(Me("NoDelay"),Boolean)
            End Get
            Set
                Me("NoDelay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property SendRecieveDelay() As Integer
            Get
                Return CType(Me("SendRecieveDelay"),Integer)
            End Get
            Set
                Me("SendRecieveDelay") = value
            End Set
        End Property
    End Class
End Namespace
