'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace REY_PressMate.Settings
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")>  _
    Partial Friend NotInheritable Class Settings_Keyence7XX
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As Settings_Keyence7XX = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings_Keyence7XX()),Settings_Keyence7XX)
        
        Public Shared ReadOnly Property [Default]() As Settings_Keyence7XX
            Get
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10.0.7.55")>  _
        Public Property Default_TCP_IP() As String
            Get
                Return CType(Me("Default_TCP_IP"),String)
            End Get
            Set
                Me("Default_TCP_IP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Enabled() As Boolean
            Get
                Return CType(Me("Enabled"),Boolean)
            End Get
            Set
                Me("Enabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9004")>  _
        Public Property Default_TCP_DataPort() As Integer
            Get
                Return CType(Me("Default_TCP_DataPort"),Integer)
            End Get
            Set
                Me("Default_TCP_DataPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9004")>  _
        Public Property Default_TCP_CommandPort() As Integer
            Get
                Return CType(Me("Default_TCP_CommandPort"),Integer)
            End Get
            Set
                Me("Default_TCP_CommandPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30000")>  _
        Public Property ReadTimeout() As Integer
            Get
                Return CType(Me("ReadTimeout"),Integer)
            End Get
            Set
                Me("ReadTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property TimeBetweenReads() As Integer
            Get
                Return CType(Me("TimeBetweenReads"),Integer)
            End Get
            Set
                Me("TimeBetweenReads") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("115200")>  _
        Public Property Default_RS232_BaudRate() As Integer
            Get
                Return CType(Me("Default_RS232_BaudRate"),Integer)
            End Get
            Set
                Me("Default_RS232_BaudRate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property Default_RS232_DataBits() As Integer
            Get
                Return CType(Me("Default_RS232_DataBits"),Integer)
            End Get
            Set
                Me("Default_RS232_DataBits") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("COM3")>  _
        Public Property Default_RS232_PortName() As String
            Get
                Return CType(Me("Default_RS232_PortName"),String)
            End Get
            Set
                Me("Default_RS232_PortName") = value
            End Set
        End Property
    End Class
End Namespace
