'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")>  _
Partial Friend NotInheritable Class Settings_Deprag
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Settings_Deprag = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings_Deprag()),Settings_Deprag)
    
    Public Shared ReadOnly Property [Default]() As Settings_Deprag
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("192.168.1.111")>  _
    Public Property SFM_IP() As String
        Get
            Return CType(Me("SFM_IP"),String)
        End Get
        Set
            Me("SFM_IP") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("44818")>  _
    Public Property SFM_Port() As String
        Get
            Return CType(Me("SFM_Port"),String)
        End Get
        Set
            Me("SFM_Port") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("JXC9")>  _
    Public Property SFM_eipProductName() As String
        Get
            Return CType(Me("SFM_eipProductName"),String)
        End Get
        Set
            Me("SFM_eipProductName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("12")>  _
    Public Property SFM_eipType() As String
        Get
            Return CType(Me("SFM_eipType"),String)
        End Get
        Set
            Me("SFM_eipType") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("209")>  _
    Public Property SFM_eipVendorID() As String
        Get
            Return CType(Me("SFM_eipVendorID"),String)
        End Get
        Set
            Me("SFM_eipVendorID") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property SFM_Enable() As Boolean
        Get
            Return CType(Me("SFM_Enable"),Boolean)
        End Get
        Set
            Me("SFM_Enable") = value
        End Set
    End Property
End Class
