'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")>  _
Partial Friend NotInheritable Class Settings_EIP
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Settings_EIP = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings_EIP()),Settings_EIP)
    
    Public Shared ReadOnly Property [Default]() As Settings_EIP
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("500")>  _
    Public ReadOnly Property EIP_DiscoveryTime() As String
        Get
            Return CType(Me("EIP_DiscoveryTime"),String)
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("192.168.1.111")>  _
    Public Property EIP_DefaultIP() As String
        Get
            Return CType(Me("EIP_DefaultIP"),String)
        End Get
        Set
            Me("EIP_DefaultIP") = value
        End Set
    End Property
End Class
